# Generated by Django 4.0.5 on 2022-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('enemy_name', models.CharField(max_length=20)),
                ('singel_6', models.CharField(max_length=20)),
                ('double_6_1', models.CharField(max_length=20)),
                ('double_6_2', models.CharField(max_length=20)),
                ('double_5', models.CharField(max_length=20)),
                ('double_5_1', models.CharField(max_length=20)),
                ('double_5_2', models.CharField(max_length=20)),
                ('double_4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('member1', models.CharField(max_length=20)),
                ('member2', models.CharField(max_length=20)),
                ('member3', models.CharField(max_length=20)),
                ('member4', models.CharField(max_length=20)),
                ('member5', models.CharField(max_length=20)),
                ('member6', models.CharField(max_length=20)),
                ('member7', models.CharField(max_length=20)),
                ('member8', models.CharField(max_length=20)),
                ('member9', models.CharField(max_length=20)),
                ('member10', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
