# Generated by Django 4.0.5 on 2022-06-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_order_team_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='singel_6',
            new_name='single_6',
        ),
    ]
