# Generated by Django 4.0.5 on 2022-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_singel_6_order_single_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='syumoku',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='syumoku',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member10',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member9',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
