# Generated by Django 4.0.5 on 2022-06-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_order_syumoku_team_syumoku_alter_team_member1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
