# Generated by Django 4.0.5 on 2022-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0005_delete_order_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syumoku', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=20)),
                ('enemy_name', models.CharField(max_length=20)),
                ('single_6', models.CharField(max_length=20)),
                ('double_6_1', models.CharField(max_length=20)),
                ('double_6_2', models.CharField(max_length=20)),
                ('double_5', models.CharField(max_length=20)),
                ('double_5_1', models.CharField(max_length=20)),
                ('double_5_2', models.CharField(max_length=20)),
                ('double_4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syumoku', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=20)),
                ('member1', models.CharField(max_length=20, null=True)),
                ('member2', models.CharField(max_length=20, null=True)),
                ('member3', models.CharField(max_length=20, null=True)),
                ('member4', models.CharField(max_length=20, null=True)),
                ('member5', models.CharField(max_length=20, null=True)),
                ('member6', models.CharField(max_length=20, null=True)),
                ('member7', models.CharField(max_length=20, null=True)),
                ('member8', models.CharField(max_length=20, null=True)),
                ('member9', models.CharField(max_length=20, null=True)),
                ('member10', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
